version: '3.3'

services:
  db:
    image: mysql
      environment:
        MYSQL_ROOT_PASSWORD: password
  webapp:
    image: spugachev/webtest:3.0
    ports:
      - 1001:3000
    deploy:
      mode: replicated
      replicas: 3