# kubectl create --save-config -f kube.yaml
# kubectl apply -f kube.yaml
# kubectl delete -f kube.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webtest-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: webtest
    spec:
      containers:
      - name: webtest
        image: spugachev/webtest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: webtest-service
spec:
  type: NodePort
  ports:
  - port: 30081
    targetPort: 3000
    nodePort: 30081
  selector:
    app: webtest