# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
	config.vm.define "srv1" do |srv1|
		srv1.vm.box = "xenji/ubuntu-17.04-server"
		srv1.vm.hostname = "srv1"
		srv1.vm.network "private_network", ip: "192.168.1.10"
		srv1.vm.network "forwarded_port", guest: 80, host: 8080
		srv1.vm.network "forwarded_port", guest: 443, host: 8443
		srv1.vm.provision :shell, path: "bootstrap.sh"
	end

	config.vm.define "srv2" do |srv2|
		srv2.vm.box="xenji/ubuntu-17.04-server"
		srv2.vm.hostname = "srv2"
		srv2.vm.network "private_network", ip: "192.168.1.20"
	end

	config.vm.define "srv3" do |srv3|
		srv3.vm.box = "xenji/ubuntu-17.04-server"
		srv3.vm.hostname = "srv3"
		srv3.vm.network "private_network", ip: "192.168.1.30"
	end
end
