version: '2'

services:
  registry:
    restart: always
    image: registry:2
    container_name: registry
    ports: 
    - 1000:5000
    environment:
      REGISTRY_HTTP_SECRET: REG1_aBJ7EQRcPEm7bGYn
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/reg.corp.spugachev.com.crt
      REGISTRY_HTTP_TLS_KEY: /certs/reg.corp.spugachev.com.key
      #REGISTRY_HTTP_TLS_LETSENCRYPT_CACHEFILE: /cache.letsencrypt
      #REGISTRY_HTTP_TLS_LETSENCRYPT_EMAIL: spugachev@gmail.com
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
    - /data/registry/data:/var/lib/registry
    - /data/registry/auth:/auth
    - /data/registry/certs:/certs:ro
